export { default as HomeLayout } from "./HomeLayout";
export { default as About } from "./About";
export { default as Landing } from './Landing';
export { default as Login } from "./Login";
export { default as Error } from "./Error";
export { default as ContactUs } from "./ContactUs";
export { default as Quote } from "./Quote";
export { default as Services } from "./Services";
export { default as SingleService } from "./SingleService";
